# Generated by Django 5.1.5 on 2025-02-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animal_description_animal_user_animal_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth0_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
