# Generated by Django 5.1.5 on 2025-02-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_auth0_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='free_uploads_remaining',
            field=models.IntegerField(default=5),
        ),
    ]
