# Generated by Django 5.1.5 on 2025-02-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_free_uploads_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
